
# CONFIGURACIÓN GENERAL
spring.application.name=MS-PAGOS
spring.profiles.active=dev

server.address=0.0.0.0
server.port=8084

# COMPATIBILIDAD SPRING CLOUD
spring.cloud.compatibility-verifier.enabled=false

# DESACTIVAR JMX
spring.jmx.enabled=false

# EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# SWAGGER / OPENAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html